### PR TITLE
Terminal notifier 2

### PR DESCRIPTION
**Pull request by shadow-identity**
Hi,
Just updated binaries to actual version of Terminal Notifier (2.0.0). Pync version was updated too.
I've also made changes to work well with Python 3.

Please review and merge it if it's is OK

Best regards,
Pavel

### CODE REVIEW

**Comment by SeTeM** [comment]
@shadow-identity, thanks for your PR!
I'll test it today

**Comment by shadow-identity** [comment]
@SeTeM Hi!
Is there some problems which can block merging of this PR? I can fix them ;)

**Comment by SeTeM** [comment]
@shadow-identity, tested, works fine. Thanks again!

**Comment by SeTeM** [comment]
@shadow-identity, I've pushed v2 to https://pypi.python.org/pypi/pync

**Comment by shadow-identity** [comment]
@SeTeM Thank you!

**Pull request merged**
